version: '3'
services:
  api:
    build:
      context: ../../
      dockerfile: ./smu-extras/docker/builds/api/Dockerfile
    volumes:
      - "../../smu-api/:/var/www/html"
    ports:
      - 3000:80
      - 443:443
    env_file:
      - ../../smu-api/.env
      
  db:
    image: mysql
    env_file:
      - ../../smu-api/.env
    volumes:
      - "../../dump:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    env_file:
      - ../../smu-api/.env
